actuators:
  leg_1_r:
    bus: 1
    id: 1
    type: GIM8115_9
    pos_default: -1.39626
  wheel_r:
    bus: 1
    id: 2
    type: GIM6010_6
    pos_default: 0.0
  leg_1_l:
    bus: 2
    id: 3
    type: GIM8115_9
    pos_default: 1.39626
  wheel_l:
    bus: 2
    id: 4
    type: GIM6010_6
    pos_default: 0.0

# Commander
x_vel_limit_mps: 1.5
yaw_vel_limit_rps: 4.0
sitting_leg_length_m: 0.07814
standing_leg_length_m: 0.3182
stand_up_duration_s: 1.0
sit_down_duration_s: 1.0

# Controller
x_kp: 5.0
pitch_kp: 30.0
x_kd: 2.0
pitch_kd: 4.5

leg_kp: 50.0
leg_kd: 5.0

yaw_kp: 10.0
yaw_kd: 0.1

link_length: 0.225
wheel_radius: 0.1
wheel_base: 0.1405
friction_coeff: 1.0

# State estimator
contact_threshold: 1.0 # Newtons
com_x: -0.05

# Main loop
loop_rate: 1000 # Hz
