actuators:
  leg_1_r:
    bus: 1
    id: 1
    type: GIM8115_9
    zero_offset_deg: -80
  wheel_r:
    bus: 1
    id: 2
    type: GIM6010_6
    zero_offset_deg: 0
  leg_1_l:
    bus: 2
    id: 3
    type: GIM8115_9
    zero_offset_deg: 80
  wheel_l:
    bus: 2
    id: 4
    type: GIM6010_6
    zero_offset_deg: 0

# Input
deadzone: 0.0

# Commander
x_vel_limit_mps: 1.0
x_acc_limit_mps2: 500.0
yaw_vel_limit_rps: 4.0
yaw_acc_limit_mps2: 800.0
sitting_leg_length_m: 0.07814
standing_leg_length_m: 0.3182
stand_up_duration_s: 0.5
sit_down_duration_s: 0.5

# Controller
k_x: 10.0
k_pitch: 40.0
k_x_vel: 5.0
k_pitch_vel: 15.0

leg_kp: 50.0
leg_kd: 5.0

yaw_kp: 0.0
yaw_kd: 1.0

roll_kp: 0.0
roll_kd: 0.0

leg_link_m: 0.225
wheel_diam_m: 0.2
wheelbase_m: 0.281
friction_coeff: 1.0

# State estimator
contact_threshold_n: 5.0
default_com_x: -0.05

# Main loop
# loop_rate_hz: 200
loop_rate_hz: 400
