actuators:
  leg_1_r:
    bus: 1
    id: 1
    type: GIM8115_9
    zero_offset_deg: -80
  wheel_r:
    bus: 1
    id: 2
    type: GIM6010_6
    zero_offset_deg: 0
  leg_1_l:
    bus: 2
    id: 3
    type: GIM8115_9
    zero_offset_deg: 80
  wheel_l:
    bus: 2
    id: 4
    type: GIM6010_6
    zero_offset_deg: 0

# Commander
x_vel_limit_mps: 1.5
yaw_vel_limit_rps: 4.0
sitting_leg_length_m: 0.07814
standing_leg_length_m: 0.3182
stand_up_duration_s: 1.0
sit_down_duration_s: 1.0

# Controller
k_x: 5.0
k_pitch: 30.0
k_x_vel: 2.0
k_pitch_vel: 4.5

leg_kp: 50.0
leg_kd: 5.0

yaw_kp: 10.0
yaw_kd: 0.1

leg_link_m: 0.225
wheel_diam_m: 0.2
wheelbase_m: 0.281
friction_coeff: 1.0

# State estimator
contact_threshold_n: 1.0
default_com_x: -0.05

# Main loop
loop_rate_hz: 200
